Device Credentials Installer
nRFCloud/utils pull request #1
Opened 2021-08-24 00:48 UTC by plskeggs

Add serial-based device credentials installer.

Update README.md.

2021-08-25 18:11 UTC, jayteemo requested changes
did you forget to add the new py file?

2021-08-25 18:11 UTC, jayteemo commented on python/modem-firmware-1.3+/create_device_credentials.py
> +    device_cert = create_device_cert(args.dv, csr, pub_key, ca_cert, ca_key)
you can remove the stuff below which has been moved into the function

2021-08-25 18:21 UTC, plskeggs commented on python/modem-firmware-1.3+/create_device_credentials.py
> +    device_cert = create_device_cert(args.dv, csr, pub_key, ca_cert, ca_key)
Good grief.  Yes.

2021-08-25 19:24 UTC, jayteemo requested changes
looks good.
i'm a python novice so i don't really have any code-related comments.
just a couple general cleanup items for log messages:
use upper case "CSV" for printed messages where appropriate.
capitalize first word of all printed messages.

2021-08-25 19:24 UTC, jayteemo commented on python/modem-firmware-1.3+/device_credentials_installer.py
> +    """\
stray `\`

2021-08-25 19:24 UTC, jayteemo commented on python/modem-firmware-1.3+/device_credentials_installer.py
> +    print(local_style('requesting CSR for sectag {}...'.format(args.sectag)))
more specifically, this is something like, "generating private key and requesting a CSR"

2021-08-25 19:24 UTC, jayteemo commented on python/modem-firmware-1.3+/device_credentials_installer.py
> +        print(error_style('unable to create CSR; does it already exist for this sectag?'))
"unable to generate private key"

2021-08-25 19:24 UTC, jayteemo commented on python/modem-firmware-1.3+/device_credentials_installer.py
> +    print(local_style('loading ca and key...'))
`CA`

2021-08-25 19:24 UTC, jayteemo commented on python/modem-firmware-1.3+/device_credentials_installer.py
> +    with open(csv_filename, mode, newline='\n') as csvfile:
would adding exception handling provide any value here?

2021-08-25 23:24 UTC, plskeggs commented
OK, made the changes.

2021-08-25 23:59 UTC, jayteemo approved these changes

2021-08-25 23:59 UTC, jayteemo commented on python/modem-firmware-1.3+/device_credentials_installer.py
> +        print(local_style('Getting to at mode...'))
`AT mode`

2021-08-25 23:59 UTC, jayteemo commented on python/modem-firmware-1.3+/device_credentials_installer.py
> +        print(local_style('{} Provisioning endpoint csv file {}...'
`CSV file`

2021-08-27 18:16 UTC, plskeggs commented
Do you want me to merge this?

2021-08-27 18:17 UTC, jayteemo commented
> Do you want me to merge this?

go for it

2021-08-27 18:18 UTC, merged